server:
  port: 8087
  servlet:
    session:
      timeout: 30
spring:
  application:
    name: roncoo-pay-spring-boot-app-reconciliation
logging:
  config: classpath:logback.xml
mybatis:
  mapper-locations: classpath*:mybatis/mapper/**/*.xml

