server:
  port: 8088
  servlet:
    session:
      timeout: 30
spring:
  application:
    name: roncoo-pay-spring-boot-app-settlement
logging:
  config: classpath:logback.xml
mybatis:
  mapper-locations: classpath*:mybatis/mapper/**/*.xml


